apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-config-files
data:
  hello-world.yaml: |
    app:
      name: hello-world
      version: 1.0.0
  hello-world-2.yaml: |
    app:
      name: hello-world-2
      version: 2.0.0