apiVersion: v1
kind: Secret
metadata:
  name: hello-world-secret-files
type: Opaque
stringData:
  secret.yaml: |
    app:
      password: mypassword
  secret2.yaml: |
    app:
      password: mypassword-2